import { useMemo, useState } from 'react'
import { api, niceDate, title } from './api'
import MapPanel from './MapPanel'
import { verifyAssignment } from './verify'
import type { Assignment, Case, CaseDetail, Finding, FollowUp, Site, Summary, User } from './types'

type Perform = <T>(path: string, method: string, body?: unknown, message?: string, selectedId?: number | null) => Promise<T | undefined>
type Props = { page: string; cases: Case[]; detail: CaseDetail | null; summary: Summary | null; sites: Site[]; openCase: (id: number) => Promise<void>; perform: Perform; refresh: () => Promise<void>; token: string; navigate: (page: 'overview' | 'cases' | 'review' | 'activity') => void }

export default function Reviewer(props: Props) {
  const { page, cases, detail, summary, sites, openCase, perform, refresh, token, navigate } = props
  const [region, setRegion] = useState('')
  const [risk, setRisk] = useState('')
  const [status, setStatus] = useState('')
  const [query, setQuery] = useState('')
  const [after, setAfter] = useState('')
  const [showCreate, setShowCreate] = useState(false)
  const [siteId, setSiteId] = useState('')
  const [excluded, setExcluded] = useState<number[]>([])
  const [inspectors, setInspectors] = useState<User[]>([])
  const filtered = useMemo(() => cases.filter(item =>
    (!region || item.site.region === region) && (!risk || item.site.risk === risk) && (!status || item.status === status) &&
    (!query || `${item.site.name} ${item.site.organization} ${item.code}`.toLowerCase().includes(query.toLowerCase())) &&
    (!after || item.created_at.slice(0, 10) >= after)), [cases, region, risk, status, query, after])

  async function openCreate() {
    setShowCreate(true)
    try { setInspectors((await api<User[]>('/users', token)).filter(item => item.role === 'inspector')) } catch { /* form remains usable */ }
  }
  async function createCase(event: React.FormEvent) {
    event.preventDefault()
    if (!siteId) return
    const created = await perform<CaseDetail>('/inspections', 'POST', { site_id: Number(siteId), excluded_inspector_ids: excluded }, 'Inspection case created.')
    if (created) { setShowCreate(false); setSiteId(''); setExcluded([]); await openCase(created.id) }
  }

  if (page === 'overview') return <><Heading kicker="OPERATIONS OVERVIEW" title="District command center" description="A live view of fictional inspection work across Nila District." action={<button className="primary" onClick={() => void openCreate()}>＋ Create case</button>} />
    {!summary ? <div className="empty-state">Loading operations summary…</div> : <>
      <div className="metrics"><Metric label="Total inspections" value={summary.total} foot="Across six demo sites" tone="navy" /><Metric label="Pending assignment" value={summary.pending} foot="Ready for randomized dispatch" tone="amber" /><Metric label="In progress" value={summary.in_progress} foot={`${summary.assigned} assigned, awaiting check-in`} tone="blue" /><Metric label="Completed" value={summary.completed} foot="Submitted by inspectors" tone="green" /><Metric label="Overdue actions" value={summary.overdue_followups} foot="Needs reviewer attention" tone="red" /></div>
      <div className="dashboard-grid"><section className="panel map-panel"><div className="panel-header"><div><div className="eyebrow">FIELD COVERAGE</div><h3>Inspection footprint</h3></div><span className="panel-chip">{summary.coverage.region}</span></div><MapPanel sites={summary.sites} /></section><section className="panel coverage-panel"><div className="eyebrow">REGIONAL COVERAGE</div><h3>Sites inspected</h3><div className="coverage-ring" style={{ '--progress': `${summary.coverage.percent}%` } as React.CSSProperties}><div><strong>{summary.coverage.percent}%</strong><span>coverage</span></div></div><p><strong>{summary.coverage.inspected_sites} of {summary.coverage.total_sites}</strong> fictional sites have a completed case.</p><div className="mini-legend"><span><i className="legend-dot green" /> Completed</span><span><i className="legend-dot amber" /> Open</span></div></section></div>
      <div className="dashboard-bottom"><section className="panel"><div className="panel-header"><div><div className="eyebrow">ATTENTION REQUIRED</div><h3>Recent findings</h3></div><button className="text-button" onClick={() => navigate('review')}>Review in queue →</button></div><FindingList findings={summary.recent_findings.slice(0, 4)} onOpen={openCase} /></section><section className="panel"><div className="panel-header"><div><div className="eyebrow">LATEST EVENTS</div><h3>Audit activity</h3></div></div><ActivityList activity={summary.activity.slice(0, 5)} /></section></div></>}
      {showCreate && <CreateModal sites={sites} siteId={siteId} setSiteId={setSiteId} excluded={excluded} setExcluded={setExcluded} inspectors={inspectors} close={() => setShowCreate(false)} submit={createCase} />}
    </>

  if (page === 'activity') return <><Heading kicker="AUDIT TRAIL" title="Recorded activity" description="Important demo actions with actor, entity, and server timestamp." />{summary ? <section className="panel activity-full"><ActivityList activity={summary.activity} /></section> : <div className="empty-state">Loading audit activity…</div>}</>

  if (page === 'review') return <><Heading kicker="REVIEW WORKSPACE" title="Findings & follow-ups" description="Review inspector findings and track the actions they generate." />
    <div className="queue-grid"><section className="panel"><div className="panel-header"><h3>Finding queue</h3><span className="panel-chip">{summary?.recent_findings.length || 0} recent</span></div><FindingList findings={summary?.recent_findings || []} onOpen={openCase} /></section><section className="panel"><div className="panel-header"><h3>Follow-up actions</h3><span className="panel-chip warn">{summary?.overdue_followups || 0} overdue</span></div>{summary?.follow_ups.length ? summary.follow_ups.map(row => <FollowUpRow key={row.id} item={row} perform={perform} refresh={refresh} />) : <div className="empty-state">No follow-up actions yet.</div>}</section></div>
    {detail && <CasePanel detail={detail} perform={perform} refresh={refresh} close={() => void openCase(detail.id)} />}</>

  return <><Heading kicker="CASE MANAGEMENT" title="Inspection cases" description="Assign, inspect, review, and follow every site record." action={<button className="primary" onClick={() => void openCreate()}>＋ Create case</button>} />
    <div className="filter-bar"><label className="search-label">Search<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Site, organization, case ID" /></label><label>Region<select value={region} onChange={event => setRegion(event.target.value)}><option value="">All regions</option>{[...new Set(sites.map(site => site.region))].map(value => <option key={value}>{value}</option>)}</select></label><label>Risk<select value={risk} onChange={event => setRisk(event.target.value)}><option value="">All risk</option>{['high', 'medium', 'low'].map(value => <option key={value}>{value}</option>)}</select></label><label>Status<select value={status} onChange={event => setStatus(event.target.value)}><option value="">All status</option>{['pending', 'assigned', 'in_progress', 'completed'].map(value => <option key={value} value={value}>{title(value)}</option>)}</select></label><label>Created after<input type="date" value={after} onChange={event => setAfter(event.target.value)} /></label></div>
    <div className="case-layout"><section className="case-list">{filtered.length ? filtered.map(item => <button key={item.id} className={`case-row ${detail?.id === item.id ? 'selected' : ''}`} onClick={() => void openCase(item.id)}><div className="case-row-top"><span className="case-code">{item.code}</span><Badge value={item.status} /></div><h3>{item.site.name}</h3><div className="case-sub">{item.site.organization} · {item.site.region}</div><div className="case-row-foot"><span className={`risk ${item.site.risk}`}>{title(item.site.risk)} risk</span><span>{item.assigned_inspector?.display_name || 'Unassigned'}</span></div></button>) : <div className="empty-state">No cases match these filters.</div>}</section><div>{detail ? <CasePanel detail={detail} perform={perform} refresh={refresh} /> : <div className="panel select-case"><div className="select-icon">◎</div><h3>Select an inspection</h3><p>Open a case to see assignment records, checklist answers, evidence, findings, and follow-ups.</p></div>}</div></div>
    {showCreate && <CreateModal sites={sites} siteId={siteId} setSiteId={setSiteId} excluded={excluded} setExcluded={setExcluded} inspectors={inspectors} close={() => setShowCreate(false)} submit={createCase} />}
  </>
}

function Heading({ kicker, title: heading, description, action }: { kicker: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-heading"><div><div className="eyebrow">{kicker}</div><h1>{heading}</h1><p>{description}</p></div>{action}</div> }
function Metric({ label, value, foot, tone }: { label: string; value: number; foot: string; tone: string }) { return <div className={`metric metric-${tone}`}><div className="metric-top"><span>{label}</span><i /></div><strong>{value.toString().padStart(2, '0')}</strong><small>{foot}</small></div> }
function Badge({ value }: { value: string }) { return <span className={`badge ${value}`}>{title(value)}</span> }
function FindingList({ findings, onOpen }: { findings: Finding[]; onOpen: (id: number) => Promise<void> }) { return findings.length ? <div className="finding-list">{findings.map(row => <button className="finding-row" key={row.id} onClick={() => void onOpen(row.case_id)}><span className={`severity ${row.severity}`}>{title(row.severity)}</span><span className="finding-main"><strong>{row.category}</strong><small>{row.description}</small></span><span className="finding-status">{title(row.review_status)}<small>{niceDate(row.created_at)}</small></span><span className="row-arrow">→</span></button>)}</div> : <div className="empty-state">No findings recorded yet.</div> }
function ActivityList({ activity }: { activity: Summary['activity'] }) { return activity.length ? <div className="timeline">{activity.map(row => <div className="timeline-item" key={row.id}><span className="timeline-dot" /><div><strong>{title(row.action)}</strong><p>{row.actor} · {row.entity_type} #{row.entity_id}{row.details && ` · ${row.details}`}</p><small>{niceDate(row.created_at)}</small></div></div>)}</div> : <div className="empty-state">No activity yet.</div> }

function CreateModal({ sites, siteId, setSiteId, excluded, setExcluded, inspectors, close, submit }: { sites: Site[]; siteId: string; setSiteId: (value: string) => void; excluded: number[]; setExcluded: (value: number[]) => void; inspectors: User[]; close: () => void; submit: (event: React.FormEvent) => Promise<void> }) { return <div className="modal-backdrop" role="presentation" onMouseDown={close}><div className="modal" role="dialog" aria-modal="true" aria-labelledby="create-title" onMouseDown={event => event.stopPropagation()}><div className="modal-header"><div><div className="eyebrow">NEW INSPECTION</div><h2 id="create-title">Create a case</h2></div><button className="icon-button" onClick={close} aria-label="Close">×</button></div><form onSubmit={event => void submit(event)}><label>Site<select value={siteId} onChange={event => setSiteId(event.target.value)} required><option value="">Select a fictional site</option>{sites.map(site => <option key={site.id} value={site.id}>{site.name} · {title(site.risk)} risk</option>)}</select></label><div className="form-note">A standard four-item checklist is added automatically. Assignment happens separately through the recorded random draw.</div><fieldset><legend>Exclude inspectors from this case (optional)</legend>{inspectors.filter(person => person.active).map(person => <label className="check-line" key={person.id}><input type="checkbox" checked={excluded.includes(person.id)} onChange={event => setExcluded(event.target.checked ? [...excluded, person.id] : excluded.filter(id => id !== person.id))} /> {person.display_name}{!person.available && ' · unavailable'}</label>)}</fieldset><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Create case</button></div></form></div></div> }

function CasePanel({ detail, perform, refresh }: { detail: CaseDetail; perform: Perform; refresh: () => Promise<void>; close?: () => void }) {
  const [reason, setReason] = useState('')
  const [remoteOutcome, setRemoteOutcome] = useState('observed')
  const [remoteNote, setRemoteNote] = useState('Simulated desk review completed.')
  const canAssign = ['pending', 'assigned'].includes(detail.status)
  async function assign() { const result = await perform<Assignment>(`/inspections/${detail.id}/assign`, 'POST', { reason: detail.assignment_history.length ? reason : undefined }, 'Assignment event recorded.', detail.id); if (result) setReason('') }
  async function remote(event: React.FormEvent) { event.preventDefault(); await perform('/remote-verification/simulate', 'POST', { case_id: detail.id, outcome: remoteOutcome, note: remoteNote }, 'Simulated remote verification recorded.', detail.id) }
  return <section className="panel detail-panel"><div className="detail-top"><div><div className="eyebrow">{detail.code}</div><h2>{detail.site.name}</h2><p>{detail.site.organization} · {detail.site.region}</p></div><Badge value={detail.status} /></div><div className="detail-metadata"><div><small>SITE ID</small><strong>{detail.site.code}</strong></div><div><small>RISK LEVEL</small><strong>{title(detail.site.risk)}</strong></div><div><small>INSPECTOR</small><strong>{detail.assigned_inspector?.display_name || 'Unassigned'}</strong></div><div><small>COORDINATES</small><strong>{detail.site.latitude.toFixed(4)}, {detail.site.longitude.toFixed(4)}</strong></div></div>
    {detail.risk_flags.length > 0 && <div className="risk-box"><strong>Priority signals</strong>{detail.risk_flags.map(flag => <div key={flag}>⚑ {flag}</div>)}</div>}
    <SectionTitle title="Assignment record" caption="Verifiable randomized dispatch" />
    {canAssign && <div className="action-box">{detail.assignment_history.length > 0 && <label>Reassignment reason<input value={reason} onChange={event => setReason(event.target.value)} placeholder="Required for a new event" /></label>}<button className="primary" onClick={() => void assign()} disabled={detail.assignment_history.length > 0 && !reason.trim()}>{detail.assignment_history.length ? 'Create reassignment event' : 'Assign eligible inspector'}</button></div>}
    {detail.assignment_history.length ? <div className="assignment-list">{detail.assignment_history.map(item => <AssignmentRow key={item.id} item={item} perform={perform} />)}</div> : <div className="empty-state compact">No assignment event yet.</div>}
    <SectionTitle title="Field inspection" caption="Client location is an untrusted signal" />
    {detail.inspection ? <div className="info-card"><div className="two-cols"><div><small>CHECK-IN</small><strong>{niceDate(detail.inspection.checkin_at)}</strong></div><div><small>GEOFENCE RESULT</small><strong>{title(detail.inspection.geofence_result)}</strong></div><div><small>REPORTED LOCATION</small><strong>{detail.inspection.client_latitude == null ? 'Not reported' : `${detail.inspection.client_latitude.toFixed(5)}, ${detail.inspection.client_longitude?.toFixed(5)}`}</strong></div><div><small>REPORTED ACCURACY / DISTANCE</small><strong>{detail.inspection.reported_accuracy_m == null ? '—' : `${Math.round(detail.inspection.reported_accuracy_m)} m`} / {detail.inspection.distance_m == null ? '—' : `${Math.round(detail.inspection.distance_m)} m`}</strong></div><div><small>SUBMITTED</small><strong>{niceDate(detail.inspection.submitted_at)}</strong></div></div></div> : <div className="empty-state compact">Inspector has not checked in.</div>}
    <div className="response-list">{detail.template.map(item => { const response = detail.responses.find(row => row.item_key === item.key); return <div className="response-row" key={item.key}><span>{item.label}{item.required && <i>Required</i>}</span><strong>{response ? title(response.answer === 'na' ? 'not applicable' : response.answer) : 'Unanswered'}</strong>{response?.note && <small>{response.note}</small>}</div> })}</div>
    <SectionTitle title="Findings" caption="Review decisions require a note" />
    {detail.findings.length ? detail.findings.map(finding => <FindingReview key={finding.id} finding={finding} followups={detail.follow_ups.filter(action => action.finding_id === finding.id)} perform={perform} caseId={detail.id} />) : <div className="empty-state compact">No findings recorded.</div>}
    <SectionTitle title="Evidence integrity" caption="Hashes identify byte changes; they do not prove capture time or location" />
    {detail.evidence.length ? detail.evidence.map(evidence => <div className="evidence-card" key={evidence.id}><div><strong>{evidence.original_filename}</strong><small>{evidence.mime_type} · {(evidence.size_bytes / 1024).toFixed(1)} KB · Server received {niceDate(evidence.server_received_at)}</small></div><div className="hash-line">SHA-256 <code>{evidence.sha256}</code></div>{evidence.client_capture_time && <small>Client-reported capture: {evidence.client_capture_time}</small>}{evidence.client_latitude != null && <small>Client-reported location: {evidence.client_latitude}, {evidence.client_longitude}</small>}</div>) : <div className="empty-state compact">No evidence uploaded.</div>}
    <SectionTitle title="Remote verification" caption="Simulation only · CCTV unavailable in MVP" /><form className="remote-form" onSubmit={event => void remote(event)}><label>Simulated outcome<select value={remoteOutcome} onChange={event => setRemoteOutcome(event.target.value)}><option value="observed">Observed</option><option value="needs_visit">Needs site visit</option><option value="inconclusive">Inconclusive</option></select></label><label>Note<input value={remoteNote} onChange={event => setRemoteNote(event.target.value)} minLength={3} required /></label><button className="secondary">Record simulated check</button></form>{detail.remote_verifications.map(row => <div className="remote-record" key={row.id}>{title(row.outcome)} · {row.note} · {niceDate(row.created_at)}</div>)}
    <button className="text-button refresh-detail" onClick={() => void refresh()}>↻ Refresh case details</button>
  </section>
}

function SectionTitle({ title: heading, caption }: { title: string; caption: string }) { return <div className="section-title"><h3>{heading}</h3><span>{caption}</span></div> }

function AssignmentRow({ item, perform }: { item: Assignment; perform: Perform }) {
  const [verification, setVerification] = useState<{ commitment: boolean; selection: boolean } | null>(null)
  const [seed, setSeed] = useState(item.seed || '')
  async function reveal() {
    const revealed = await perform<Assignment>(`/assignments/${item.id}/reveal-seed`, 'POST', {}, 'Demo seed revealed for verification.', item.case_id)
    if (revealed?.seed) { setSeed(revealed.seed); setVerification(await verifyAssignment(revealed)) }
  }
  async function verify() { setVerification(await verifyAssignment({ ...item, seed })) }
  return <div className="assignment-card"><div className="assignment-head"><strong>Event #{item.event_number}</strong><span>{niceDate(item.selected_at)}</span></div><div className="assignment-person">Selected: <strong>{item.selected_inspector.display_name}</strong></div><div className="assignment-meta">Eligible weights: {item.eligible.map(candidate => `${candidate.id} × ${candidate.weight}`).join(', ')}<br />Algorithm: {item.algorithm}{item.reason && <><br />Reason: {item.reason}</>}</div><div className="hash-line">Commitment <code>{item.commitment}</code></div><div className="assignment-actions">{seed ? <button className="secondary small" onClick={() => void verify()}>Verify in this browser</button> : <button className="secondary small" onClick={() => void reveal()}>Reveal demo seed & verify</button>}{verification && <span className={verification.commitment && verification.selection ? 'verify-ok' : 'verify-bad'}>{verification.commitment ? '✓ Commitment matches' : '✕ Commitment mismatch'} · {verification.selection ? '✓ Selection reproduced' : '✕ Selection mismatch'}</span>}</div>{seed && <div className="seed-line">Revealed seed <code>{seed}</code></div>}</div>
}

function FindingReview({ finding, followups, perform, caseId }: { finding: Finding; followups: FollowUp[]; perform: Perform; caseId: number }) {
  const [reviewStatus, setReviewStatus] = useState('accepted')
  const [reviewNote, setReviewNote] = useState('')
  const [owner, setOwner] = useState('')
  const [dueDate, setDueDate] = useState('')
  async function review(event: React.FormEvent) { event.preventDefault(); const result = await perform(`/findings/${finding.id}/review`, 'POST', { status: reviewStatus, note: reviewNote }, 'Finding review recorded.', caseId); if (result) setReviewNote('') }
  async function followup(event: React.FormEvent) { event.preventDefault(); const result = await perform(`/findings/${finding.id}/follow-ups`, 'POST', { owner, due_date: dueDate, status: 'open' }, 'Follow-up created.', caseId); if (result) { setOwner(''); setDueDate('') } }
  return <div className="finding-card"><div className="finding-card-top"><span className={`severity ${finding.severity}`}>{title(finding.severity)}</span><strong>{finding.category}</strong><Badge value={finding.review_status} /></div><p>{finding.description}</p><small>Recommended: {finding.recommended_action}</small>{finding.review_note && <div className="review-note">Review note: {finding.review_note}</div>}<form className="inline-form" onSubmit={event => void review(event)}><label>Decision<select value={reviewStatus} onChange={event => setReviewStatus(event.target.value)}><option value="accepted">Accepted</option><option value="needs_clarification">Needs clarification</option><option value="dismissed">Dismissed</option></select></label><label>Required note<input value={reviewNote} onChange={event => setReviewNote(event.target.value)} required minLength={3} placeholder="Reason for decision" /></label><button className="secondary small">Save review</button></form><div className="followup-subtitle">FOLLOW-UP ACTIONS</div>{followups.map(row => <div className="followup-mini" key={row.id}><Badge value={row.status} /> {row.owner} · due {row.due_date}{row.overdue && <strong> · Overdue</strong>}</div>)}<form className="inline-form" onSubmit={event => void followup(event)}><label>Owner or department<input value={owner} onChange={event => setOwner(event.target.value)} required minLength={2} placeholder="Maintenance cell" /></label><label>Due date<input type="date" value={dueDate} onChange={event => setDueDate(event.target.value)} required /></label><button className="secondary small">Create follow-up</button></form></div>
}

function FollowUpRow({ item, perform, refresh }: { item: FollowUp; perform: Perform; refresh: () => Promise<void> }) {
  const [status, setStatus] = useState(item.status)
  const [note, setNote] = useState('')
  async function update(event: React.FormEvent) { event.preventDefault(); const result = await perform(`/follow-ups/${item.id}`, 'PUT', { status, note }, 'Follow-up status updated.'); if (result) { setNote(''); await refresh() } }
  return <div className="followup-row"><div className="followup-row-head"><strong>{item.owner}</strong><Badge value={item.status} /></div><div className={item.overdue ? 'overdue-text' : ''}>Due {item.due_date}{item.overdue && ' · Overdue'}</div><small>Finding #{item.finding_id}</small><details><summary>Status history ({item.history.length})</summary><div className="history-list">{item.history.map((row, index) => <div key={index}>{title(row.status)} · {row.actor} · {niceDate(row.at)}{row.note && ` · ${row.note}`}</div>)}</div></details><form className="followup-update" onSubmit={event => void update(event)}><select aria-label="New follow-up status" value={status} onChange={event => setStatus(event.target.value)}><option value="open">Open</option><option value="in_progress">In progress</option><option value="closed">Closed</option></select><input aria-label="Status change note" value={note} onChange={event => setNote(event.target.value)} placeholder="Required status note" minLength={3} required /><button className="secondary small">Update</button></form></div>
}
